# Generated by Django 4.1.2 on 2023-09-11 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Updated',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تولید'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.TextField(max_length=3000, verbose_name='جزییات خبر'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='تصویر خبر'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1, verbose_name='وضعییت'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
    ]
