# Generated by Django 4.1.2 on 2023-09-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_alter_articles_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ManyToManyField(to='news.category', verbose_name='دسته\u200cبندی'),
        ),
    ]
