# Generated by Django 4.1.2 on 2023-09-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_articles_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-published'], 'verbose_name': 'خبر', 'verbose_name_plural': 'اخبار'},
        ),
    ]
