# Generated by Django 4.1.2 on 2023-09-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_category_sub_cat_alter_articles_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sub_cat',
            new_name='parent',
        ),
    ]
